### ISSUE TITLE
TODO: dev/new-ui

### ISSUE THREAD

**Issue by trippjoe** [open-goal/launcher#52]
- [ ]  Fonts
- [ ]  Better UI when copying data files
- [ ]  General/Misc. error handling screen
    - [ ]  Revise Reinstall & Outdated to use general error screen
- [ ]  Connect release notes to F.E
- [ ] User Testing

**Comment by xTVaser** [comment]
https://github.com/open-goal/launcher/pull/104
